statefulSet:
  serviceName: service
  serviceAccountName: service-account
  replicas: 1
  containers:
    - name: mysql
      image:
        repository: mysql
        tag: "8"
      ports:
        - name: mysql
          containerPort: 3306
      # readinessProbe:
      #   exec:
      #     command:
      #       - /bin/sh
      #       - -c
      #       - mysql -u root --password=$MYSQL_ROOT_PASSWORD -e "grant all privileges on *.* to '$MYSQL_USER'@'%';FLUSH PRIVILEGES;"
      #   initialDelaySeconds: 30
      #   periodSeconds: 10
      #   timeoutSeconds: 2
      #   failureThreshold: 5
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1024Mi
      envFromSecret:
        - secretName: auth-secret
          envs:
            - name: MYSQL_ROOT_PASSWORD
              key: ROOT_PASSWORD
            - name: MYSQL_USER
              key: USERNAME
            - name: MYSQL_PASSWORD
              key: PASSWORD
      volumeMounts:
        - name: storage
          mountPath: /var/lib/mysql
          subPath: mysql
  volumes:
    - name: storage
      type: pvc
      typeName: storage-pvc

infisicalSecrets:
  - name: infisical-auth-secret
    serviceTokenSecretName: service-token
    secretsPath: /mysql
    secretName: auth-secret

pvcs:
  - name: storage-pvc
    storageClassName: local-path-persistent
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem

serviceAccount:
  name: service-account

services:
  - name: service
    type: ClusterIP
    ports:
      - name: mysql
        protocol: TCP
        port: 3306

vaultSecrets:
  - name: auth-secret
    path: secrets/mysql
    templates:
      ROOT_PASSWORD: "{% .Secrets.root_password %}"
      USERNAME: "{% .Secrets.username %}"
      PASSWORD: "{% .Secrets.password %}"